name: test for py3

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.9", "3.12"]
      fail-fast: true

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install tox
        run: pip install tox

      - name: Run tox targets for ${{ matrix.python }}
        run: |
          pyFlag=$(echo ${{ matrix.python }} | tr -d .)
          for e in `tox -l | grep "$pyFlag-" | grep -v lint`; do tox -e $e; done

      - name: Upload coverage to Codecov
        if: ${{ matrix.python == '3.9' }}
        uses: codecov/codecov-action@v5
        with:
          files: .coverage/coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
